### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by JakeMakesStuff** [discord/erlpack#29]
It'd be nice to have Go support in erlpack. I'll take a shot at implementing it and making a pull request, if I get stuck I'll say here!

**Comment by JakeMakesStuff** [comment]
Getting the hang of this, I should have a PR by the end of today!

![Progress!](https://freethewump.us/aellapyat.png?key=pxeufcxnqdmhptknhofnuldslhefduax)

**Comment by JakeMakesStuff** [comment]
Ok maybe not tonight.

Packing works (with unit tests), unpacking takes a lot more work as I found out!

**Comment by jamiebuilds** [comment]
Moved to #31
